package hosts

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/TacoContent/ironstate/sdk/becomeexec"
	"github.com/TacoContent/ironstate/sdk/handler"
)

// BecomeCommand is an internal re-entry marker used only when become asks this
// plugin to perform its final privileged file write.
const BecomeCommand = "--ironstate-plugin-become"

func writeWithBecome(path, contents string, become handler.Become) error {
	temporary, err := os.CreateTemp("", "ironstate-hosts-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer func() { _ = os.Remove(temporaryPath) }()
	if _, err := temporary.WriteString(contents); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	executable, err := os.Executable()
	if err != nil {
		return err
	}
	wrappedExecutable, args, err := becomeexec.WrapForBecome(become, executable, []string{BecomeCommand, path, temporaryPath})
	if err != nil {
		return err
	}
	output, err := exec.Command(wrappedExecutable, args...).CombinedOutput() //nolint:gosec // executable and paths are generated by this process
	if err != nil {
		return fmt.Errorf("write hosts file with become: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func RunWriteHelper(args []string) int {
	if len(args) != 3 || args[0] != BecomeCommand {
		return 2
	}
	contents, err := os.ReadFile(args[2]) //nolint:gosec // path is the private temporary file created by this process
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	if err := os.WriteFile(args[1], contents, 0o644); err != nil { //nolint:gosec // destination is the hosts file requested by this handler
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	return 0
}
